name: Blastbot Bridge
version: 1.0.2
slug: blastbot_bridge
description: Blastbot Bridge for Home Assistant
arch:
  - amd64
  - i386
  - armhf
  - armv7
  - aarch64
startup: services
init: false
url: https://blastbot.io
webui: http://[HOST]:[PORT:5555]/
ingress: true
ingress_port: 5555
services:
  - mqtt:need
options:
  external_mqtt_broker_address: ""
  discovery_prefix: "homeassistant"
  blastbot_cloud_url: https://cloud.blastbot.io
  blastbot_cloud_api_user: ""
  blastbot_cloud_api_password: ""
schema:
  external_mqtt_broker_address: "str"
  discovery_prefix: "str"
  blastbot_cloud_url: "url?"
  blastbot_cloud_api_user: "email?"
  blastbot_cloud_api_password: "password?"

homeassistant_api: true
auth_api: true
panel_icon: "mdi:circle-double"
discovery:
  - mqtt
